### ISSUE TITLE
Bug: Card no se rellena data del video programado futuro

### ISSUE THREAD

**Issue by giolapietra** [reevolutiva/twchr-dev#22]

**Comment by giolapietra** [comment]
Issue duplicado en #9

**Comment by giolapietra** [comment]
Esto es el mismo problema descrito en https://github.com/reevolutiva/twchr-dev/issues/37 o parte de su propia corrección, por lo que el ticket está duplicado.

**Comment by jerexxypunto** [comment]
Cuando se importan de manera automatica las series no se estan importando de manera automatica los chapters.

**Comment by giolapietra** [comment]
Ticket duplicado en 9
