### ISSUE TITLE
Al activar el plugin y no estar conectado, se genera una lista de errores en Twitcher Dashboard

### ISSUE THREAD

**Issue by giolapietra** [reevolutiva/twchr-dev#35]
Enmascarar con algún mensaje "Not Connected whit Twitch.tv: Run - Setup"

![Image](https://user-images.githubusercontent.com/76657648/211073863-21fdfae2-c5de-4087-b59d-a9ac930d1a85.png)

**Comment by jerexxypunto** [comment]
¿Cuando desintalas el plugin borrando todos los datos pasa eso verdad?

**Comment by giolapietra** [comment]
Eso pasa cuando activas el plugin y aún no hiciste el Setup

**Comment by jerexxypunto** [comment]
entiendo.
