### ISSUE TITLE
Twitcher Card Muestra datos incorrectos

### ISSUE THREAD

**Issue by giolapietra** [reevolutiva/twchr-dev#37]
1. El mensaje "Esta serie no tiene capítulos debe aparece sólo cuando se ha seleccionado serie" (Error acá: https://egosapiens.net/wp-admin/post.php?post=1227&action=edit)
2. Los capítulos se despliegan de forma incorrecta

![Image](https://user-images.githubusercontent.com/76657648/211078533-948c14e4-3f6d-4784-a5ad-9ad0114c159b.png)

**Comment by giolapietra** [comment]
Se abrió otro ticket para este mismo Issue https://github.com/reevolutiva/twchr-dev/issues/22

**Comment by jerexxypunto** [comment]
![Image](https://user-images.githubusercontent.com/65317114/212314799-44ac1c27-c5f8-48e6-9d3c-72e1f7ff8eed.png)

Mostrar solo cuando exisrtan series en twitcg

**Comment by jerexxypunto** [comment]
![Image](https://user-images.githubusercontent.com/65317114/212315261-7fe27d48-68b5-45ae-8786-43dd8cea8e00.png)

Display none si selecciono un serie

**Comment by jerexxypunto** [comment]
![Image](https://user-images.githubusercontent.com/65317114/212315783-db3f9461-d8bf-44c8-b183-4d11b7f82a56.png)

id recurring false serie name -> streaming name

**Comment by giolapietra** [comment]
@jerexxypunto Dos errores importantes acá: 

Al ingresar a la card, aparece este error PHP
![Image](https://user-images.githubusercontent.com/76657648/212498688-bcffabc8-e759-4df7-8756-f1eb505191f8.png)

Luego
Para que el listado de capítulo aparezca, debo hacer dos CLicks el nombre de la serie, sólo con uno no los muestra: 
![Image](https://user-images.githubusercontent.com/76657648/212498613-1a94c3b9-3e40-4d82-9722-b80339ff6c37.png)

**Comment by giolapietra** [comment]
Este problema continúa e impide que podamos publicar el plugin. Lo Publicaré por partes, para que los resolvamos rápido.
1. Error PHP


![Image](https://user-images.githubusercontent.com/76657648/212773898-d63494c3-6477-47c8-aed9-268ec9b96f1b.png)

Según Chat GPT:
Este error indica que hay una restricción de open_basedir en efecto en su servidor. open_basedir es una configuración de seguridad en PHP que limita el acceso de un script a ciertas rutas del sistema de archivos. El error específico que se muestra en Query monitor indica que el archivo "/en.js" y "/en_dlg.js" no están dentro de las rutas permitidas especificadas en la configuración de open_basedir.
En este caso, estos archivos se encuentran fuera de las rutas permitidas que son "/tmp:/home/twitcher.pro/", lo cual impide que WordPress pueda acceder a ellos.
Para resolver este problema, se pueden configurar las rutas permitidas en open_basedir para incluir la ruta de los archivos afectados, o desactivar la configuración de open_basedir. Sin embargo, es importante tener en cuenta que open_basedir es una medida de seguridad importante y su desactivación puede exponer su servidor a riesgos. Es recomendable consultar con su administrador de sistemas o con un especialista en seguridad antes de tomar cualquier acción.

Hay varias soluciones posibles para este problema:

Una de ellas sería modificar la configuración de open_basedir en el servidor para incluir la ruta de los archivos a los que el plugin intenta acceder. Sin embargo, esto puede representar un riesgo para la seguridad del servidor y es recomendable consultar con un especialista en seguridad antes de realizar cambios.

Otra opción sería modificar el código del plugin para que utilice una ruta absoluta o relativa a una ruta permitida en lugar de la ruta actual. Esto debería permitir que el plugin acceda a los archivos necesarios.

También se puede considerar desactivar la configuración de open_basedir. Sin embargo, es importante tener en cuenta que esta configuración es una medida de seguridad importante y su desactivación puede exponer su servidor a riesgos.

En cualquier caso, es importante revisar el código del plugin y asegurarse de que está utilizando rutas permitidas y considerando las limitaciones de seguridad.
--------------
Habría que revisar que todas las rutas tengan sus respectivas variables.

**Comment by giolapietra** [comment]
Sigue manifestando el problema que bloquea un Click de la selección de fecha

![Image](https://user-images.githubusercontent.com/76657648/212774734-6ddbd338-e836-4dea-8de4-275d5c8d588a.png)
El botón "Save" no hace nada, y para seleccionar tengo que hacer click en "Serie name" 


![Image](https://user-images.githubusercontent.com/76657648/212774842-25b87933-ace0-4087-941b-9bffe82550c6.png)
![Image](https://user-images.githubusercontent.com/76657648/212774841-3b91af88-449c-49b0-94b5-afb9992803dc.png)

**Comment by jerexxypunto** [comment]
Sí no hay ninguna serie importada, el ajax que trae series no funciona, tal como muestra la imagen de arriba.

**Comment by jerexxypunto** [comment]
Si cambio el titulo del post hago clicl en el save dice esto:


![Image](https://user-images.githubusercontent.com/65317114/212945913-fc68a657-bc32-4c1a-a6f4-bfeccb30a0c2.png)

**Comment by jerexxypunto** [comment]
Cuando asignamos un youtube embed no se preselecciona la pestaña de VOD.



![Image](https://user-images.githubusercontent.com/65317114/213177919-d5ae305a-66d8-4c41-b803-25ee14ea7a0b.png)

**Comment by jerexxypunto** [comment]
Al asignar la serie Serie-reev esta no asigna:


![Image](https://user-images.githubusercontent.com/65317114/213228465-3364f370-0191-4f8b-9285-3ba9630f0d25.png)

Sin embargo la serie Despertando Conciencia si se asgina:


![Image](https://user-images.githubusercontent.com/65317114/213228755-4e9ba325-08ef-499b-bdef-4b5b54d603a8.png)


Teroiso que puede ser poque el nombre de Serie-reev lleva un gion, pero no estoy seguro, esta sujeto a debug

**Comment by giolapietra** [comment]
Corregido
