### ISSUE TITLE
Error al redireccionar

### ISSUE THREAD

**Issue by giolapietra** [reevolutiva/twchr-dev#40]
Tampoco se actualiza la página, por lo que da la impresión que no se había creado, pero si actualizas, se creó dos veces

![Image](https://user-images.githubusercontent.com/76657648/211084209-c8c590c3-7541-4dc8-9fbe-b288ff3af07e.png)

**Comment by jerexxypunto** [comment]
si bloqueamos la pagina de series ¿ponemos el boton de import series en la card?

**Comment by giolapietra** [comment]
Esta pantalla no estará disponible para el usuario final
