### ISSUE TITLE
Error Crítico de Wordpress

### ISSUE THREAD

**Issue by giolapietra** [reevolutiva/twchr-dev#41]
Al entrar a editar una serie, se le asigna fecha y hora y al asignar Twitch Catory y presionar enter muestra error crítico de WordPress

![Image](https://user-images.githubusercontent.com/76657648/211084640-0160c634-76fb-4d1b-8bc9-271889ea116a.png)

**Comment by giolapietra** [comment]
Reabro ticket:
desapareció la asignación de categoría Twitch y los capítulos.

![Image](https://user-images.githubusercontent.com/76657648/211561597-3b525e8c-592f-4483-a82d-d4224a14f514.png)

**Comment by jerexxypunto** [comment]
Yo me meto a esa misma serie y no veo el error, entiendo entonces que este resuelto.

Dejare este Issue en "In progress" a la espera de tu validacion


![Image](https://user-images.githubusercontent.com/65317114/211793945-41873a74-233d-47bc-8673-ab495e191e73.png)

**Comment by giolapietra** [comment]
Puede haberse resuelto. Una vez hagas el commit y las pruebas, verificamos esto y lo cerramos
