### ISSUE TITLE
Al asignar un capítulo a un nuevo Streaming...

### ISSUE THREAD

**Issue by giolapietra** [reevolutiva/twchr-dev#43]
Pregunta: "Reolad Page?"
Comportamiento esperado -> Save Post -> Reload Page automático. 
Si se acepta el reload, se pierde lo escrito en los campos. 

![Image](https://user-images.githubusercontent.com/76657648/211095761-07cc7626-1539-48c0-8e29-3caa490eba4f.png)

**Comment by giolapietra** [comment]
Problema Persiste

![Image](https://user-images.githubusercontent.com/76657648/212498473-4e813f45-ff66-4e33-bb6d-0dfec28b4ccc.png)

**Comment by jerexxypunto** [comment]
![Image](https://user-images.githubusercontent.com/65317114/217014297-cc81e96b-715f-4704-a0e5-f14f1a8910f1.png)

Luego de migrar la logica a wp.apiRequest no se esta asignando correctamente un schedule segment, mi teoria es que no esta tomando el post_id ya que en la respuesta llega un post_id 0 siendo que en este ejemplo es 1167
