### ISSUE TITLE
Se guardan custom fields vacios y eso da error

### ISSUE THREAD

**Issue by jerexxypunto** [reevolutiva/twchr-dev#47]

**Comment by giolapietra** [comment]
¿De qué se trata este error? 
Dónde ocurre?
Print de pantalla?

**Comment by jerexxypunto** [comment]
Ya lo reparé

**Comment by giolapietra** [comment]
Para la próxima, antes de abrir el ticker sigue estos pasos:
https://github.com/orgs/reevolutiva/discussions/48
