### ISSUE TITLE
la actualizacion de los chapters nos e hace en tiempo real

### ISSUE THREAD

**Issue by jerexxypunto** [reevolutiva/twchr-dev#55]
Cuando se ejecuta la actualizacion de las series antes de que renderice la card.

La actualizacion de la taxonomia se hace correectamente pero no se visualiza en tiempo real los cambio, pues requiere recargar 2 veces la página

Ya descubri porque sucede, estoy pensando en como remediarlo

**Comment by giolapietra** [comment]
https://github.com/reevolutiva/twchr-dev/issues/55
