### ISSUE TITLE
Asignación de capítulos a Serie

### ISSUE THREAD

**Issue by giolapietra** [reevolutiva/twchr-dev#9]
Se debe poder asignar un capítulo a una un streaming. Una vez que se selecciona la serie, aparece el select para el capítulo.
Datetime Streaming debe mostrar SOLO las fechas y horas de la active serie en select "serie"

**Comment by giolapietra** [comment]
Este error continúa

**Comment by giolapietra** [comment]
A la hora de presionar el botón de Save para asignarle un capítulo aparece el mensaje para abandonar la pagina sin editar. 

![Image](https://user-images.githubusercontent.com/76657648/211556317-4b913fa6-1bd9-41be-8255-505cb3182580.png)

Luego, vuelve a redirigir a la misma página en para crear un nuevo streaming, no vuelve a completar los datos del mismo streaming en el que estamos.

**Comment by giolapietra** [comment]
en https://egosapiens.net/wp-admin/post-new.php?post_type=twchr_streams ahora, no se muestran las series, a pesar de haber capítulos disponibles el Twitch

**Comment by jerexxypunto** [comment]
No comprendo muy bien este Issue, porque a mi si me muestra solo los capitulos que corresponden a la serie seleccionada.



![Image](https://user-images.githubusercontent.com/65317114/211793402-17432afe-85c4-4cf7-85ce-15a82890b993.png)

**Comment by giolapietra** [comment]
im portante es [seguir el protocolo de pruebas ](https://github.com/orgs/reevolutiva/discussions/33)y que funcione correctamente

**Comment by jerexxypunto** [comment]
Cuando creamos un streaming singular, se crea exitosamente pero no se redirecciona a la pagina de ese streaming

**Comment by jerexxypunto** [comment]
Cuando el nombre de la serie tiene 2 palabras la funcion de preseleecion no funciona.



![Image](https://user-images.githubusercontent.com/65317114/212100764-cfa8a354-75de-4f18-adc0-61c6f7b1dd63.png)

**Comment by jerexxypunto** [comment]
No se asigna serie


![Image](https://user-images.githubusercontent.com/65317114/212340616-65ebbda8-c1ea-4feb-991f-6ad12f4e4bcc.png)

**Comment by giolapietra** [comment]
Twitcher Card no muestra hora en capítulo asignado @jerexxypunto 
<img width="944" alt="Captura de pantalla 2023-01-14 a la(s) 18 29 54" src="https://user-images.githubusercontent.com/76657648/212497867-e5c57674-e983-4596-8843-437ad777b228.png">

**Comment by giolapietra** [comment]
Cambiamos el evento "click" por el evento "change"
